name: Update scene table, character occurrences, and deploy to GitHub Pages

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: 1.26.5

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@e2f99d4b3685b0da93f97e1b86ad8fab81105098 # v3
        with:
          root_file: main.tex
          working_directory: src

      - name: Update scene list and character occurrences
        run: |
          cd go-scripts
          go run . create-scene-table --src ../src
          go run . update-scene-occurrence-subtitles --src ../src
          go run . extract-page-numbers --src ../src --pdf "../src/main.pdf"
          cd ..

      - name: Push changes
        uses: actions-x/commit@803b20e5b72c0425eb7919c42c321e67c5bc5d2d # v6
        with:
          email: github-actions[bot]@users.noreply.github.com
          username: github-actions[bot]
          message: "Update scene list and character occurrences"
          files: src/*.tex

      - name: Re-compile LaTeX document
        if: github.ref == 'refs/heads/main'
        uses: xu-cheng/latex-action@e2f99d4b3685b0da93f97e1b86ad8fab81105098 # v3
        with:
          root_file: main.tex
          working_directory: src

      # From https://github.com/latextemplates/scientific-thesis-template/blob/main/.github/workflows/build-and-publish-with-latexmk.yml
      - name: Gather build artifacts
        if: github.ref == 'refs/heads/main'
        run: mkdir build && cp src/main.pdf build/play.pdf && cp -r docs/* build/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: ${{ github.event.head_commit.message }}
          enable_jekyll: true
